git:
  depth: 1

notifications:
  email: false

os: linux
sudo: required
language: generic
services: docker

env:
  global:
    - ACTION=gmake
    - PLATFORM=x64
   #- PREMAKEARGS="--cc=clang"

  matrix:
    - CONFIG=debug
      CONFIG_UPPER=Debug
      SUFFIX=-d

    - CONFIG=release
      CONFIG_UPPER=Release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  target_branch: travis-${CONFIG}-${PLATFORM}
  repo: S6066/Teal-binaries
  local_dir: ${TRAVIS_BUILD_DIR}/buildresults/result/
  name: Travis CI
  on:
    branch: master

install: docker build -t teal .
script:
  - docker run --name Teal -v /:/ teal
      bash -c "
        cd ${TRAVIS_BUILD_DIR}/extlibs/include &&
        mkdir -p nazara && cd /tmp &&

        curl https://github.com/S6066/NazaraEngine/releases/download/v0.4.x/NazaraEngine-gcc-7.3.0-linux64-nightly.7z -Lo nazara.7z &&
        7z x nazara.7z &&
        cp -r /tmp/package/include/Nazara ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/Nazara && cp -r /tmp/package/include/NDK ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/NDK &&

        cd ${TRAVIS_BUILD_DIR}/extlibs/lib/ &&
        mkdir -p ${ACTION} && cd ${ACTION} &&
        mkdir -p ${PLATFORM} && cd ${PLATFORM} &&
        mkdir -p nazara && mkdir -p micropather &&
        cp /tmp/package/bin/${PLATFORM}/*.so ${TRAVIS_BUILD_DIR}/extlibs/lib/${ACTION}/${PLATFORM}/nazara &&

        cd micropather &&
        cp -r ${TRAVIS_BUILD_DIR}/extlibs/src/micropather/** ./ &&
        
        ./premake5-linux64 ${PREMAKEARGS} ${ACTION} &&
        sudo make config=${CONFIG}_${PLATFORM} &&
        cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a ./ &&
        cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a ${TRAVIS_BUILD_DIR}/extlibs/lib/${ACTION}/${PLATFORM}/micropather &&


        cd ${TRAVIS_BUILD_DIR}/build &&
        ./premake5-linux64 ${PREMAKEARGS} ${ACTION} &&
        cd ${ACTION} &&
        sudo make -j4 config=${CONFIG}_${PLATFORM}
      "

#" # Fix weird colorations
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo chmod +x .travis_discord_webhook.sh
  - ./.travis_discord_webhook.sh success $WEBHOOK_URL

  - cd ${TRAVIS_BUILD_DIR}/build/${ACTION}
  - mkdir result
  - cp ${CONFIG_UPPER}/${PLATFORM}/TealDemo ./result/TealDemo

  - cd result
  - cp /tmp/package/bin/${PLATFORM}/NazaraAudio${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraCore${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraGraphics${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraLua${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraNetwork${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraNoise${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraPhysics2D${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraPhysics3D${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraRenderer${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraSDK${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraSDKServer${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraUtility${SUFFIX}.so ./
  - cp /tmp/package/bin/${PLATFORM}/NazaraPlatform${SUFFIX}.so ./
  - cp -r ${TRAVIS_BUILD_DIR}/wdirs/data ./

  - cd ${TRAVIS_BUILD_DIR}
  - mkdir buildresults
  - cd buildresults
  - cp -r ${TRAVIS_BUILD_DIR}/build/${ACTION}/result/* ./

  - tar -zcvf tealdemo.tar.gz *
  - mkdir result
  - mv tealdemo.tar.gz result

  - cd result
  - printf "Travis CI Build ${TRAVIS_JOB_NUMBER} (${CONFIG} ${PLATFORM})\nCommit hash - ${TRAVIS_COMMIT}\n\nCommit message:\n${TRAVIS_COMMIT_MESSAGE}" > commit-info.txt

after_failure:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo chmod +x .travis_discord_webhook.sh
  - ./.travis_discord_webhook.sh failure $WEBHOOK_URL