notifications:
  email:
    recipients:
      - samy6066@yahoo.fr
    on_success: never
    on_failure: never

language: cpp
compiler: clang
os: linux

sudo: required
dist: trusty

branches:
  only:
  - master

install:
  - cd ${TRAVIS_BUILD_DIR}/extlibs/include
  - mkdir nazara && mkdir micropather
  - cd nazara
  - curl http://teal.esy.es/nazara/NazaraEngine-0.1.1-linux-x64.tar.gz -o nazara.tar.gz
  - tar -xvzf nazara.tar.gz
  - mv ./include/Nazara Nazara && mv ./include/NDK NDK
  - sudo cp ./bin/x64/*.so /usr/lib/
  - cd ${TRAVIS_BUILD_DIR}/extlibs/lib/
  - mkdir clang && cd clang
  - mkdir x86
  - mkdir x64 && cd x64
  - mkdir nazara && mkdir micropather
  - cd micropather
  - curl https://github.com/leethomason/MicroPather/raw/master/micropather.h -o micropather.h
  - curl https://github.com/leethomason/MicroPather/raw/master/micropather.cpp -o micropather.cpp
  - cp ${TRAVIS_BUILD_DIR}/extlibs/src/micropather/premake5.lua ./
  - cp ${TRAVIS_BUILD_DIR}/build/premake5-linux64 ./
  - ./premake5-linux64 --cc=clang gmake
  - make
  - ls
  - sudo cp ./*.so /usr/lib/
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - ./premake5-linux64 --cc=clang gmake

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make