notifications:
  email:
    on_success: never
    on_failure: never

language: cpp
compiler: g++
os: linux

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

env:
  global:
    - COMPILER=g++-5
    
  matrix:
    - CONFIG=debug
      CONFIG_UPPER=Debug

#   - CONFIG=release
#     CONFIG_UPPER=Release

branches:
  only:
  - master

before_install:
  - sudo apt-get install libc6-dev
  - sudo apt-get install gcc-5-multilib g++-5-multilib

install:
  - cd ${TRAVIS_BUILD_DIR}/extlibs/include
  - mkdir nazara && mkdir micropather
  - cd nazara
  - curl http://teal.esy.es/nazara/NazaraEngine-0.1.1-linux-x64.tar.gz -o nazara.tar.gz
  - tar -xzf nazara.tar.gz
  - mv ./include/Nazara Nazara && mv ./include/NDK NDK
  - cd ${TRAVIS_BUILD_DIR}/extlibs/lib/
  - mkdir gmake && cd gmake
  - mkdir x64 && cd x64
  - mkdir nazara && mkdir micropather
  - cd nazara
  - mv ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/x64/*.so ./
  - cd ../micropather
  - curl http://teal.esy.es/micropather/micropather.h -o micropather.h
  - curl http://teal.esy.es/micropather/micropather.cpp -o micropather.cpp
  - cp ./micropather.h ${TRAVIS_BUILD_DIR}/extlibs/include/micropather/
  - cp ${TRAVIS_BUILD_DIR}/extlibs/src/micropather/premake5.lua ./
  - cp ${TRAVIS_BUILD_DIR}/build/premake5-linux64 ./
  - ./premake5-linux64 gmake
  - make config=${CONFIG}_x64 CC=${COMPILER}
  - mv bin/x64/${CONFIG_UPPER}/* ./

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - ./premake5-linux64 gmake
  - g++ --version

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make config=${CONFIG}_x64 CC=${COMPILER}