notifications:
  email:
    recipients:
      - samy6066@yahoo.fr
    on_success: never
    on_failure: never

language: cpp
compiler: clang
os: linux

branches:
  only:
  - master

install:
  - cd ${TRAVIS_BUILD_DIR}/extlibs/include
  - mkdir nazara && mkdir micropather
  - cd nazara
  - curl https://github.com/DigitalPulseSoftware/NazaraEngine/releases/download/v0.1.1/NazaraEngine-0.1.1-linux-x64.tar.gz -o nazara.tar.gz
  - file nazara.tar.gz
  - tar -xvf nazara.tar.gz
  - mv ./include/Nazara Nazara && mv ./include/NDK NDK
  - cd ${TRAVIS_BUILD_DIR}/extlibs/lib/
  - mkdir clang && cd clang
  - mkdir x86
  - mkdir x64 && cd x64
  - mkdir nazara && mkdir micropather
  - cd nazara
  - mv ${TRAVIS_BUILD_DIR}/extlibs/include/lib/x64/*.lib ./
  - cd ../micropather
  - curl https://github.com/leethomason/MicroPather/raw/master/micropather.h -o micropather.h
  - curl https://github.com/leethomason/MicroPather/raw/master/micropather.cpp -o micropather.cpp
  - mv ../../../../src/micropather/premake5.lua ./
  - ${TRAVIS_BUILD_DIR}/build/premake5 --cc=clang gmake
  - make
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - premake5-linux64 --cc=clang gmake

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - ./configure && make