git:
  depth: 3

notifications:
  email:
    on_success: never
    on_failure: never

language: cpp
compiler: g++
os: linux

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5-multilib
      - libopenal-dev
      - libc6-dev
      - libsndfile1-dev
      - libxcb-cursor-dev
      - libxcb-ewmh-dev
      - libxcb-randr0-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libx11-dev
      - libfreetype6-dev
      - mesa-common-dev
      - libgl1-mesa-dev
      - libassimp-dev

env:
  global:
    - COMPILER=g++-5
    - ACTION=gmake
    - PLATFORM=x64
    
  matrix:
    - CONFIG=debug
      CONFIG_UPPER=Debug
      SUFFIX=-d

    - CONFIG=release
      CONFIG_UPPER=Release

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  target_branch: travis-binaries-${PLATFORM}
  repo: S6066/Teal-binaries
  local_dir: ${TRAVIS_BUILD_DIR}/buildresults/result/
  name: Travis CI
  on:
    branch: master

before_install:
  - cd /usr
  - sudo mkdir lib64 && cd lib64
  - sudo mkdir local  
  - export CXX="g++-5"
  - export CC="gcc-5"
  - sudo bash -c "find ${TRAVIS_BUILD_DIR} -type d -exec chmod 777 {} \;"
  - sudo bash -c "find ${TRAVIS_BUILD_DIR} -type f -exec chmod 777 {} \;"

install:
  - cd ${TRAVIS_BUILD_DIR}/extlibs/include
  - mkdir nazara && mkdir micropather
  - cd nazara
  - curl https://nazara.digitalpulsesoftware.net/files/NazaraEngine-0.3-linux-${PLATFORM}.tar.gz -o nazara.tar.gz
  - tar -xzf nazara.tar.gz
  - mv include/Nazara Nazara && mv include/NDK NDK
  - cd ${TRAVIS_BUILD_DIR}/extlibs/lib/
  - mkdir gmake && cd gmake
  - mkdir ${PLATFORM} && cd ${PLATFORM}
  - mkdir nazara && mkdir micropather
  - cd nazara
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/*.so /usr/lib
  - cd ../micropather
  - curl http://teal.esy.es/micropather/micropather.h -o micropather.h
  - curl http://teal.esy.es/micropather/micropather.cpp -o micropather.cpp
  - cp ./micropather.h ${TRAVIS_BUILD_DIR}/extlibs/include/micropather/
  - cp -r ${TRAVIS_BUILD_DIR}/extlibs/src/micropather/** ./
  - cp ${TRAVIS_BUILD_DIR}/build/premake5-linux${PLATFORM} ./
  - sudo bash -c "./premake5-linux${PLATFORM} gmake"
  - sudo make config=${CONFIG}_x${PLATFORM}
  - cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a ./
  - sudo cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a /usr/lib

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - sudo bash -c "./premake5-linux${PLATFORM} ${ACTION}"

script:
  - cd ${TRAVIS_BUILD_DIR}/build/${ACTION}
  - sudo make -j4 config=${CONFIG}_${PLATFORM}

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build/${ACTION}
  - sudo mkdir result
  - sudo cp ${CONFIG_UPPER}/${PLATFORM}/TealDemo ./result/TealDemo
  - cd result
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraAudio${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraCore${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraGraphics${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraLua${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraNetwork${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraNoise${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraPhysics2D${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraPhysics3D${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraRenderer${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraSDK${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraSDKServer${SUFFIX}.so ./
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/NazaraUtility${SUFFIX}.so ./
  - sudo ls ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/
  - sudo ls ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin
  - sudo ls ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/
  - sudo cp -r ${TRAVIS_BUILD_DIR}/wdirs/data ./
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir buildresults
  - cd buildresults
  - cp -r ${TRAVIS_BUILD_DIR}/build/${ACTION}/result/* ./
  - tar -zcvf tealdemo.tar.gz *
  - mkdir result
  - mv tealdemo.tar.gz result
  - cd result
  - touch commit-info
  - printf "Travis CI Build ${TRAVIS_JOB_NUMBER}\nCommit hash - ${TRAVIS_COMMIT}\n\nCommit message:\n${TRAVIS_COMMIT_MESSAGE}" > commit-info
