git:
  depth: 3

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  target_branch: travis-binaries
  repo: Teal-binaries
  local_dir: ${TRAVIS_BUILD_DIR}/buildresults/
  name: Travis CI
  on:
    branch: master

language: cpp
compiler: g++
os: linux

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5-multilib
      - libopenal-dev
      - libc6-dev
      - libsndfile1-dev
      - libxcb-cursor-dev
      - libxcb-ewmh-dev
      - libxcb-randr0-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libx11-dev
      - libfreetype6-dev
      - mesa-common-dev
      - libgl1-mesa-dev
      - libassimp-dev
      - p7zip-full

env:
  global:
    - COMPILER=g++-5
    - ACTION=gmake
    - PLATFORM=x64
    
  matrix:
    - CONFIG=debug
      CONFIG_UPPER=Debug
      SUFFIX=-d

    - CONFIG=release
      CONFIG_UPPER=Release

branches:
  only:
  - master

before_install:
  - cd /usr
  - sudo mkdir lib64 && cd lib64
  - sudo mkdir local  
  - export CXX="g++-5"
  - export CC="gcc-5"
  - sudo bash -c "find ${TRAVIS_BUILD_DIR} -type d -exec chmod 777 {} \;"
  - sudo bash -c "find ${TRAVIS_BUILD_DIR} -type f -exec chmod 777 {} \;"

install:
  - cd ${TRAVIS_BUILD_DIR}/extlibs/include
  - mkdir nazara && mkdir micropather
  - cd nazara
  - curl https://nazara.digitalpulsesoftware.net/files/NazaraEngine-0.3-linux-${PLATFORM}.tar.gz -o nazara.tar.gz
  - tar -xzf nazara.tar.gz
  - mv include/Nazara Nazara && mv include/NDK NDK
  - cd ${TRAVIS_BUILD_DIR}/extlibs/lib/
  - mkdir gmake && cd gmake
  - mkdir ${PLATFORM} && cd ${PLATFORM}
  - mkdir nazara && mkdir micropather
  - cd nazara
  - sudo cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/*.so /usr/lib
  - cd ../micropather
  - curl http://teal.esy.es/micropather/micropather.h -o micropather.h
  - curl http://teal.esy.es/micropather/micropather.cpp -o micropather.cpp
  - cp ./micropather.h ${TRAVIS_BUILD_DIR}/extlibs/include/micropather/
  - cp -r ${TRAVIS_BUILD_DIR}/extlibs/src/micropather/** ./
  - cp ${TRAVIS_BUILD_DIR}/build/premake5-linux64 ./
  - sudo bash -c "./premake5-linux64 gmake"
  - sudo make config=${CONFIG}_x64
  - cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a ./
  - sudo cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a /usr/lib

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - sudo bash -c "./premake5-linux64 ${ACTION}"

script:
  - cd ${TRAVIS_BUILD_DIR}/build/${ACTION}
  - sudo make -j4 config=${CONFIG}_x64

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build/${ACTION}
  - mkdir result
  - cp ${CONFIG_UPPER}/${PLATFORM}/TealDemo result/
  - cd result
  - cp ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/bin/${PLATFORM}/*.so ./
  - cp -r ${TRAVIS_BUILD_DIR}/wdirs ./
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir buildresults
  - cd buildresults
  - cp -r ${TRAVIS_BUILD_DIR}/build/${ACTION}/result ./
  - 7z a TealDemo.7z *
  - mkdir "build ${TRAVIS_JOB_NUMBER} (${TRAVIS_COMMIT})"
  - mv TealDemo.7z "build ${TRAVIS_JOB_NUMBER} (${TRAVIS_COMMIT})"