git:
  depth: 1

notifications:
  email: false

os: linux
sudo: required
dist: trusty
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-7
      - p7zip-full
      - libassimp-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libopenal-dev
      - libsndfile1-dev
      - libx11-dev
      - libxcb-cursor-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - mesa-common-dev

env:
  global:
    - ACTION=gmake
    - PLATFORM=x64
   #- PREMAKEARGS="--cc=clang"

  matrix:
    - CONFIG=debug
      CONFIG_UPPER=Debug
      SUFFIX=-d

    - CONFIG=release
      CONFIG_UPPER=Release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  target_branch: travis-${CONFIG}-${PLATFORM}
  repo: S6066/Teal-binaries
  local_dir: ${TRAVIS_BUILD_DIR}/buildresults/result/
  name: Travis CI
  on:
    branch: master

before_install:
  - sudo update-alternatives
    --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
    --slave /usr/bin/g++ g++ /usr/bin/g++-7
    --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7
    --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7
    --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
  - sudo update-alternatives --auto gcc

install:
  - cd ${TRAVIS_BUILD_DIR}/extlibs/include
  - mkdir -p nazara && cd /tmp

  - curl https://github.com/S6066/NazaraEngine/releases/download/v0.4.x/NazaraEngine-gcc-7.3.0-linux64-nightly.7z -Lo nazara.7z
  - 7z x nazara.7z
  - cp package/include/Nazara ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/Nazara && cp package/include/NDK ${TRAVIS_BUILD_DIR}/extlibs/include/nazara/NDK
  - cp /tmp/package/bin/${PLATFORM}/*.so ${TRAVIS_BUILD_DIR}/extlibs/lib/${ACTION}/${PLATFORM}/nazara

  - cd ${TRAVIS_BUILD_DIR}/extlibs/lib/
  - mkdir -p ${ACTION} && cd ${ACTION}
  - mkdir -p ${PLATFORM} && cd ${PLATFORM}
  - mkdir -p nazara && mkdir -p micropather

  - cd micropather
  - cp -r ${TRAVIS_BUILD_DIR}/extlibs/src/micropather/** ./
  
  - ./premake5-linux64 ${PREMAKEARGS} ${ACTION}
  - sudo make config=${CONFIG}_${PLATFORM}
  - cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a ./
  - cp bin/${PLATFORM}/${CONFIG_UPPER}/libmicropather${SUFFIX}.a ${TRAVIS_BUILD_DIR}/extlibs/lib/${ACTION}/${PLATFORM}/micropather

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - ./premake5-linux64 ${PREMAKEARGS} ${ACTION}

script:
  - cd ${TRAVIS_BUILD_DIR}/build/${ACTION}
  - sudo make -j4 config=${CONFIG}_${PLATFORM}

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo chmod +x .travis_discord_webhook.sh
  - ./.travis_discord_webhook.sh success $WEBHOOK_URL

  - cd ${TRAVIS_BUILD_DIR}/build/${ACTION}
  - sudo mkdir result
  - sudo cp ${CONFIG_UPPER}/${PLATFORM}/TealDemo ./result/TealDemo

  - cd result
  - sudo cp /tmp/package/bin/${PLATFORM}/NazaraAudio${SUFFIX}.so ./
  - sudo cp /tmp/package/bin/${PLATFORM}/NazaraCore${SUFFIX}.so ./
  - sudo cp /tmp/package/bin/${PLATFORM}/NazaraGraphics${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraLua${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraNetwork${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraNoise${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraPhysics2D${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraPhysics3D${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraRenderer${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraSDK${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraSDKServer${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraUtility${SUFFIX}.so ./
  - sudo cp /tmp/bin/${PLATFORM}/NazaraPlatform${SUFFIX}.so ./
  - sudo cp -r ${TRAVIS_BUILD_DIR}/wdirs/data ./

  - cd ${TRAVIS_BUILD_DIR}
  - mkdir buildresults
  - cd buildresults
  - cp -r ${TRAVIS_BUILD_DIR}/build/${ACTION}/result/* ./

  - tar -zcvf tealdemo.tar.gz *
  - mkdir result
  - mv tealdemo.tar.gz result

  - cd result
  - printf "Travis CI Build ${TRAVIS_JOB_NUMBER} (${CONFIG} ${PLATFORM})\nCommit hash - ${TRAVIS_COMMIT}\n\nCommit message:\n${TRAVIS_COMMIT_MESSAGE}" > commit-info.txt

after_failure:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo chmod +x .travis_discord_webhook.sh
  - ./.travis_discord_webhook.sh failure $WEBHOOK_URL