skip_commits:
  files:
    - .gitignore
    - .travis.yml
    - .travis_discord_webhook.sh
    - Dockerfile_*
    - LICENSE
    - README.md
    - build.md
    - coding_style.md
  message: /.\[skip ci\]./

version: '{branch} v0.x (#{build})'
skip_tags: true
image: Visual Studio 2017

notifications:
  - provider: Slack
    incoming_webhook:
      secure: Chl4vnW7unY6EQvnjtGkll8IgVFCQEuy71L458sTgxJ/0EoT1aa0mizZg4zes6aTnBAxxS+OY/oc/dFaR/XBXCZ5PyLiJPaduINDN2rey/IlEgTSXHFuBEWGibjxZ1HU6mDxOSKcyG8ZQ/VqZH/CsVtIGOZBJya+IWZ2EmjmWhHxoWeunE0Tq7j6AXXZizmN
    on_build_success: true 
    on_build_failure: true 
    on_build_status_changed: false

build:
  verbosity: minimal

environment:
  TOOLSET: vs2017
  matrix:
    - CONFIG: Debug
      SUFFIXDLL: -d.dll
      SUFFIXLIB: -d.lib
      PLATFORM: x86
      PLATFORMNAME: Win32

    - CONFIG: Debug
      SUFFIXDLL: -d.dll
      SUFFIXLIB: -d.lib
      PLATFORM: x64
      PLATFORMNAME: x64

    - CONFIG: Release
      SUFFIXDLL: .dll
      SUFFIXLIB: .lib
      PLATFORM: x64
      PLATFORMNAME: x64

    - CONFIG: Release
      SUFFIXDLL: .dll
      SUFFIXLIB: .lib
      PLATFORM: x86
      PLATFORMNAME: Win32

install:
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/include
  - mkdir nazara && cd nazara
  - curl https://github.com/S6066/NazaraEngine/releases/download/v0.4.x/NazaraEngine-msvc15-win-nightly.7z -Lo nazara.7z
  - 7z x nazara.7z
  - mv package/include/Nazara Nazara && mv package/include/NDK NDK
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/lib/
  - cd %TOOLSET% && cd %PLATFORM%
  - mkdir nazara && cd nazara
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/lib/%PLATFORM%/*.lib ./

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - premake5.exe %TOOLSET%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build/%TOOLSET%
  - msbuild "Teal.sln" /verbosity:minimal /p:Configuration=%CONFIG% /p:Platform=%PLATFORMNAME% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%/build/
  - mkdir result && cd result
  - mkdir Teal
  - mv ../%TOOLSET%/%CONFIG%/%PLATFORM%/Teal.exe Teal/Teal-%CONFIG%-%PLATFORM%.exe
  - cd Teal
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraAudio%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraCore%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraGraphics%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraLua%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraNetwork%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraNoise%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraPhysics2D%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraPhysics3D%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraRenderer%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraSDK%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraSDKServer%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraUtility%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/NazaraPlatform%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/assimp.dll ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/libsndfile-1.dll ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/Newton.dll ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/package/bin/%PLATFORM%/soft_oal.dll ./
  - cd ..
  - mv %APPVEYOR_BUILD_FOLDER%/wdirs/data ./
  - echo Appveyor Build %APPVEYOR_BUILD_NUMBER% (%CONFIG% %PLATFORM%) [ID %APPVEYOR_BUILD_ID%] on branch %APPVEYOR_REPO_BRANCH%\nCommit hash - %APPVEYOR_REPO_COMMIT%\n\nCommit message:\n%APPVEYOR_REPO_COMMIT_MESSAGE% > commit-info.log
  - 7z a Teal.7z * && cd ../..

artifacts:
  - path: build/result/Teal.7z
    name: 'Teal-%CONFIG%-%PLATFORM%-%APPVEYOR_REPO_COMMIT%'