skip_commits:
  files:
    - .gitignore
    - .travis.yml
    - .travis_discord_webhook.sh
    - .todo.txt
    - Dockerfile_*
    - LICENSE
    - README.md
    - build.md
    - coding_style.md
  message: /.\[skip ci\]./

version: '{branch} v0.x (#{build})'
skip_tags: true
image: Visual Studio 2017

notifications:
  - provider: Slack
    incoming_webhook:
      secure: Chl4vnW7unY6EQvnjtGkll8IgVFCQEuy71L458sTgxJ/0EoT1aa0mizZg4zes6aTnBAxxS+OY/oc/dFaR/XBXCZ5PyLiJPaduINDN2rey/IlEgTSXHFuBEWGibjxZ1HU6mDxOSKcyG8ZQ/VqZH/CsVtIGOZBJya+IWZ2EmjmWhHxoWeunE0Tq7j6AXXZizmN
    on_build_success: true 
    on_build_failure: true 
    on_build_status_changed: false

build:
  verbosity: minimal

environment:
  TOOLSET: vs2017
  matrix:
    - CONFIG: Debug
      SUFFIXDLL: -d.dll
      SUFFIXLIB: -d.lib
      PLATFORM: x86
      PLATFORMNAME: Win32

    - CONFIG: Debug
      SUFFIXDLL: -d.dll
      SUFFIXLIB: -d.lib
      PLATFORM: x64
      PLATFORMNAME: x64

    - CONFIG: Release
      SUFFIXDLL: .dll
      SUFFIXLIB: .lib
      PLATFORM: x64
      PLATFORMNAME: x64

    - CONFIG: Release
      SUFFIXDLL: .dll
      SUFFIXLIB: .lib
      PLATFORM: x86
      PLATFORMNAME: Win32

install:
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/include
  - mkdir nazara && cd nazara
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - curl https://github.com/S6066/NazaraEngine/releases/download/v0.4.y/NazaraEngine-msvc14.1-win-nightly.7z -Lo NazaraEngine.7z
  - 7z x NazaraEngine.7z -oNazaraEngine
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/lib/
  - cd %TOOLSET% && cd %PLATFORM%
  - mkdir nazara && cd nazara

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - premake5.exe --lib-toolset=%TOOLSET% install_nazara
  - premake5.exe %TOOLSET%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build/%TOOLSET%
  - msbuild "Teal.sln" /verbosity:minimal /p:Configuration=%CONFIG% /p:Platform=%PLATFORMNAME% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%/build/
  - premake5.exe --package-config=%CONFIG%_%PLATFORM% --package-action=vs2017 package
  - cp -r %APPVEYOR_BUILD_FOLDER%/package_%CONFIG%_%PLATFORM% result
  - cd result
  - echo Appveyor Build %APPVEYOR_BUILD_NUMBER% (%CONFIG% %PLATFORM%) [ID %APPVEYOR_BUILD_ID%] on branch %APPVEYOR_REPO_BRANCH%\nCommit hash - %APPVEYOR_REPO_COMMIT%\n\nCommit message:\n"%APPVEYOR_REPO_COMMIT_MESSAGE%" > commit-info.log
  - 7z a Teal.7z * && cd ../..

artifacts:
  - path: build/result/Teal.7z
    name: 'Teal-%CONFIG%-%PLATFORM%-%APPVEYOR_REPO_COMMIT%'