skip_commits:
  files:
    - .travis.yml
    - LICENSE
    - README.md
    - build.md
    - coding_style.md
  message: /.\[skip ci\]./

version: '{branch} v0.0.1 (#{build})'
skip_tags: true
os: Visual Studio 2015

environment:
  TOOLSET: vs2015
  matrix:
    - CONFIG: Debug
      SUFFIXDLL: -d.dll
      SUFFIXLIB: -d.lib
      PLATFORM: x86
      PLATFORMNAME: Win32

    - CONFIG: Debug
      SUFFIXDLL: -d.dll
      SUFFIXLIB: -d.lib
      PLATFORM: x64
      PLATFORMNAME: x64

    - CONFIG: Release
      SUFFIXDLL: .dll
      SUFFIXLIB: .lib
      PLATFORM: x64
      PLATFORMNAME: x64

    - CONFIG: Release
      SUFFIXDLL: .dll
      SUFFIXLIB: .lib
      PLATFORM: x86
      PLATFORMNAME: Win32

install:
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/include
  - mkdir nazara && mkdir micropather
  - cd nazara
  - curl https://nazara.digitalpulsesoftware.net/files/NazaraEngine-0.3-msvc14-%PLATFORM%.7z -o nazara.7z
  - 7z x nazara.7z
  - mv include/Nazara Nazara && mv include/NDK NDK
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/lib/
  - mkdir %TOOLSET% && cd %TOOLSET%
  - mkdir %PLATFORM% && cd %PLATFORM%
  - mkdir nazara && mkdir micropather
  - cd nazara
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/lib/%PLATFORM%/*.lib ./
  - cd ../micropather
  - curl http://teal.esy.es/micropather/micropather.h -o micropather.h
  - curl http://teal.esy.es/micropather/micropather.cpp -o micropather.cpp
  - cp micropather.h %APPVEYOR_BUILD_FOLDER%/extlibs/include/micropather/
  - cp %APPVEYOR_BUILD_FOLDER%/extlibs/src/micropather/premake5.lua ./
  - cp %APPVEYOR_BUILD_FOLDER%/build/premake5.exe ./
  - premake5.exe %TOOLSET%
  - msbuild "Micropather.sln" /verbosity:minimal /p:Configuration=%CONFIG% /p:Platform=%PLATFORMNAME% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - mv bin/%PLATFORM%/%CONFIG%/micropather%SUFFIXLIB% ./

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - premake5.exe %TOOLSET%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build/%TOOLSET%
  - msbuild "TealDemo.vcxproj" /verbosity:minimal /p:Configuration=%CONFIG% /p:Platform=%PLATFORMNAME% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%/build/
  - mkdir result && cd result
  - mkdir TealDemo
  - mv ../%TOOLSET%/%CONFIG%/%PLATFORM%/TealDemo.exe TealDemo/TealDemo-%CONFIG%-%PLATFORM%.exe
  - cd TealDemo
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/%PLATFORM%/Nazara*%SUFFIXDLL% ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/%PLATFORM%/assimp.dll ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/%PLATFORM%/libsndfile-1.dll ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/%PLATFORM%/Newton.dll ./
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/%PLATFORM%/soft_oal.dll ./
  - cd ..
  - mv %APPVEYOR_BUILD_FOLDER%/wdirs/data ./
  - 7z a TealDemo.7z * && cd ../..

artifacts:
  - path: build/result/TealDemo.7z
    name: 'TealDemo-%CONFIG%-%PLATFORM%-%APPVEYOR_REPO_COMMIT%'