skip_commits:
  files:
    - .travis.yml
    - LICENSE
    - README.md
  message: /.\[skip ci\]./


os:
  - Visual Studio 2015

platform:
  - x64

environment:
  TOOLSET: vs2015
  matrix:
      - CONFIG: Debug
        SUFFIX: -d

      - CONFIG: Release

install:
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/include
  - mkdir nazara && mkdir micropather
  - cd nazara
  - curl http://teal.esy.es/nazara/NazaraEngine-0.2.1-msvc14-%PLATFORM%.7z -o nazara.7z
  - 7z x nazara.7z
  - mv include/Nazara Nazara && mv include/NDK NDK
  - cd %APPVEYOR_BUILD_FOLDER%/extlibs/lib/
  - mkdir %TOOLSET% && cd %TOOLSET%
  - mkdir %PLATFORM% && cd %PLATFORM%
  - mkdir nazara && mkdir micropather
  - cd nazara
  - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/lib/%PLATFORM%/*.lib ./
  - cd ../micropather
  - curl http://teal.esy.es/micropather/micropather.h -o micropather.h
  - curl http://teal.esy.es/micropather/micropather.cpp -o micropather.cpp
  - cp micropather.h %APPVEYOR_BUILD_FOLDER%/extlibs/include/micropather/
  - cp %APPVEYOR_BUILD_FOLDER%/extlibs/src/micropather/premake5.lua ./
  - cp %APPVEYOR_BUILD_FOLDER%/build/premake5.exe ./
  - premake5.exe %TOOLSET%
  - msbuild "Micropather.sln" /verbosity:minimal /p:Configuration=%CONFIG% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - mv bin/%PLATFORM%/%CONFIG%/micropather%SUFFIX%.lib ./

before_build:
    - cd %APPVEYOR_BUILD_FOLDER%/build
    - premake5.exe %TOOLSET%

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%/build
    - msbuild "Teal.sln" /verbosity:minimal /p:Configuration=%CONFIG% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd %APPVEYOR_BUILD_FOLDER%/build/
    - mkdir result && cd result
    - mkdir TealDemo
    - mv ../vs2015/%CONFIG%/x64/TealDemo.exe TealDemo/
    - cd TealDemo
    - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/x64/Nazara*%SUFFIX%.dll ./
    - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/x64/assimp.dll ./
    - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/x64/libsndfile-1.dll ./
    - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/x64/Newton.dll ./
    - mv %APPVEYOR_BUILD_FOLDER%/extlibs/include/nazara/bin/x64/soft_oal.dll ./
    - cd ..
    - mv %APPVEYOR_BUILD_FOLDER%/wdirs/data ./
    - 7z a TealDemo.7z * && cd ../..

artifacts:
    - path: build/result/TealDemo.7z
      name: 'TealDemo-%CONFIG%-%PLATFORM%-%APPVEYOR_REPO_COMMIT%'